version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /data
http:
  addr: :80
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
